version: '3'
volumes:
  dados: 
networks:
  banco:
  web:
  fila:
services:
  db:
    image: postgres:13
    container_name: db
    environment:
      - "POSTGRES_PASSWORD=123456"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=db_email"
    volumes:
      # Volume dos dados
      # - ./db:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
    ports:
      - "5432:5432"
  frontend:
    image: nginx:1.13
    container_name: frontend
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do proxy reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80 
    networks:
      - web
    depends_on:
      - app
  # Aplicação
  app: 
    image: python:3.6
    container_name: backend
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash /app/app.sh
    networks:
     - banco
     - web
     - fila
    depends_on:
     - db
     - queue
    environment:
      - "APP_DB=db_email"
      - "APP_PWD=123456"
      - "APP_USER=postgres"
      - "APP_HOST=db"
      - "REDIS_HOST=queue"
    ports: 
      - 8080:8080

  queue:
    image: redis:3.2
    networks:
      - fila
    ports: 
      - 6379:6379 


  worker: 
    container_name: Service
    image: python:3.6
    volumes:
      # Worker
      - ./worker:/worker
    working_dir: /worker
    command: bash ./app.sh
    networks:
      - fila
    depends_on:
      - queue




      





  

        
